# Generated by Django 5.2.17 on 2026-10-09 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0088_alter_credentials_credential_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditTransaction',
        ),
    ]
