# Generated by Django 5.2.17 on 2026-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0090_remove_out_of_credits_event_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='platform',
            field=models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft'), ('email', 'Email')], max_length=255),
        ),
    ]
