# Generated by Django 5.2.17 on 2026-10-09 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_backfill_is_managed_zoom_oauth_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='autopay_amount_to_purchase_cents',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='autopay_charge_failure_data',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='autopay_charge_task_enqueued_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='autopay_enabled',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='autopay_stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='autopay_threshold_centricredits',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='centicredits',
        ),
    ]
