# Generated by Django 5.2.17 on 2026-10-09 10:53

import bots.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0091_email_calendar_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('source', models.CharField(choices=[('imap', 'Imap'), ('http', 'Http')], max_length=16)),
                ('message_id', models.CharField(max_length=998)),
                ('sender', models.CharField(blank=True, max_length=320)),
                ('subject', models.CharField(blank=True, max_length=1024)),
                ('size_bytes', models.IntegerField()),
                ('raw_file', models.FileField(blank=True, null=True, storage=bots.storage.StorageAlias('recordings'), upload_to='')),
                ('state', models.IntegerField(choices=[(1, 'Received'), (2, 'Processed'), (3, 'Ignored'), (4, 'Failed')], default=1)),
                ('outcome', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('updated', 'Updated'), ('cancelled', 'Cancelled'), ('partial', 'Partial'), ('no_invitation', 'No Invitation'), ('no_meeting_url', 'No Meeting Url'), ('past_meeting', 'Past Meeting'), ('all_day_event', 'All Day Event'), ('stale_update', 'Stale Update'), ('calendar_reply', 'Calendar Reply'), ('bot_creation_failed', 'Bot Creation Failed'), ('unauthorized_sender', 'Unauthorized Sender'), ('unauthenticated_sender', 'Unauthenticated Sender'), ('auto_submitted', 'Auto Submitted'), ('loop', 'Loop'), ('rate_limited', 'Rate Limited'), ('too_large', 'Too Large'), ('error', 'Error')], max_length=64, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('auth_results', models.JSONField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=list)),
                ('reply_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('calendar_events', models.ManyToManyField(blank=True, related_name='inbound_emails', to='bots.calendarevent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_emails', to='bots.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'sender', 'created_at'], name='inbound_email_sender_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'message_id'), name='unique_inbound_email_message_id')],
            },
        ),
        migrations.CreateModel(
            name='RecurringSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=1024)),
                ('sequence', models.IntegerField(default=0)),
                ('ics', models.TextField()),
                ('name', models.CharField(blank=True, max_length=1024)),
                ('meeting_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('attendees', models.JSONField(blank=True, default=list)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('horizon_end', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.CharField(blank=True, max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_series', to='bots.calendar')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('calendar', 'uid'), name='unique_recurring_series_uid')],
            },
        ),
    ]
